services:
  nginx:
    image: nginx:alpine
    container_name: organizations_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - organizations_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: organizations_php
    volumes:
      - ./:/var/www/html
    networks:
      - organizations_network
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: organizations_postgres
    environment:
      POSTGRES_DB: organizations_catalog
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - organizations_network

volumes:
  postgres_data:

networks:
  organizations_network:
    driver: bridge

